import { Box, IconButton, Image, ListItem, UnorderedList } from '@chakra-ui/react'
import { RiHome2Line } from 'react-icons/ri'
import axios from 'axios'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Blog } from '../../components/blog'
import styles from '../../styles/Home.module.css'


const Home: NextPage = () => {
  const hello="nishisako"
  axios.get("https://zipcloud.ibsnet.co.jp/api/search?zipcode=7830060").then((value)=>{
    console.log(value)
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>Welcome my blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Box className={styles.header} position={'fixed'} align={"center"} top={"0px"} height={"70px"} width={"100vw"} bg={"#f6f1eb"}>
        <Box  display={'flex'} justifyContent={"space-between"}>
            <IconButton
              // colorScheme='blue'
              // backgroundColor={"white"}
              aria-label='Home button'
              icon={<RiHome2Line />}
              fontSize='30px'
              variant={'ghost'}
            />
            <Image mt={"3px"} left={"calc(50vw - 40px)"} position={"absolute"} width={"160px"}  borderRadius={"10px"} src={"logo.png"}></Image>
        </Box>
      </Box>

      <Blog title={"title"}></Blog>
      {/* <Blog title={"title2"}></Blog> */}

      <footer className={styles.footer}>
        <div className={styles.footersub}>
          <h1 className={styles.profiletitle}>
           I'm もにょ
          </h1>
          <p className={styles.profiletext}>
          今年の目標は、
            <UnorderedList listStyleType={"square"}>
              <ListItem>ハーブを植える</ListItem>
              <ListItem>ブログを開設する</ListItem>
              <ListItem>脱毛を契約する</ListItem>
              <ListItem>泳げるようになる</ListItem>
              <ListItem>証券口座を開設する</ListItem>
            </UnorderedList>
          </p>
        </div>
      </footer>
    </div>
  )
}

export default Home
