import { Box, Image } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { NextRouter, useRouter } from 'next/router'
import styles from '../styles/Home.module.css'
import { Button } from './button'

const Home: NextPage = () => {
  const hello="nishisako"

  const router:NextRouter=useRouter()
  
  const pushbutton=() => {
    console.log("push done")
  }

  


  interface Blog{
    title:string
    content:string
    articleId?:number
  }

  const blog:{title:string,content:string}={
    title:"title",
    content:"this is content"
  }

  const showBlog=({title,content}: Blog)=>{
    console.log(title)
  }

  showBlog({title:"a", content:"b", articleId:3})



  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box position={'fixed'} align={"center"} borderRadius={"10px"} top={"0px"} height={"100px"} width={"100vw"} bg={"#f7f0dc"}>
        <Image mt={"3px"} src={"logo.png"}></Image>
      </Box>


      <main className={styles.main}>
        <Box onClick={pushbutton} height={"100px"} width={"300px"} border={"solid 1px black"} borderRadius={"10px"}>
          {/* <Link href={
            {
              pathname:"/blog",
              query:{
                id:1
              }
            }
          }>
            <a>Title: </a>
          </Link> */}
          
        </Box>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
